<?php

$fieldGroup = array (
	'key' => 'group_5891f5155dd48',
	'title' => 'QuizMaster Emails',
	'fields' => array (
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5891f6c9cd5d1',
			'label' => 'Key',
			'name' => 'qm_email_key',
			'type' => 'text',
			'instructions' => 'Enter only lowercase and underscores such as "student_completion".',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => 1,
			'message' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'key' => 'field_5891f52665936',
			'label' => 'Enabled',
			'name' => 'qm_email_enabled',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'quizmaster_completed_quiz' => 'Quiz Completion',
				'quizmaster_completed_quiz_100_percent' => 'Quiz Completion with 100% Score',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_5891f70ecd5d2',
			'label' => 'Trigger',
			'name' => 'qm_email_trigger',
			'type' => 'select',
			'instructions' => 'Choose the action that will trigger the email to be sent. Actions fire at key points during the use of QuizMaster such as completion of a quiz.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5893a98dab7e2',
			'label' => 'From Email',
			'name' => 'qm_email_from',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5891f593cd5cd',
			'label' => 'Recipients',
			'name' => 'qm_email_recipients',
			'type' => 'text',
			'instructions' => 'Enter recipient email(s) separated by a comma: email1@example.com, email2@example.com.

Available shortcodes: [quiztaker_email]',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_5891f5accd5ce',
			'label' => 'Subject',
			'name' => 'qm_email_subject',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'html' => 'HTML',
				'plain' => 'Plain Text',
				'multipart' => 'Multipart',
			),
			'default_value' => array (
				0 => 'html',
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
			'key' => 'field_5891f5f9cd5cf',
			'label' => 'Email Type',
			'name' => 'qm_email_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'quizmaster_email',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
);
